Update head 2022.1.0
oneapi-src/oneapi-ci pull request #51
Opened 2021-12-21 14:07 UTC by daniil-mazur

Switch to 2021.1.0/2021.1.1 Release

2021-12-21 17:09 UTC, mmzakhar requested changes

2021-12-21 17:09 UTC, mmzakhar commented on .github/workflows/build_all.yml
> +      #run: scripts/cache_exclude_windows.sh
There's a syntax error here: this step doesn't have a required 'run' key.

2021-12-21 18:40 UTC, mmzakhar commented on .github/workflows/build_all.yml
>        if: steps.cache-install.outputs.cache-hit != 'true'
This 'if' dependency on the cache-install step should be commented if the step is commented

2021-12-21 19:07 UTC, merged

2022-01-07 02:57 UTC, alalek commented
> Switch to 2021.1.0/2021.1.1 Release

2021 -> 2022 (just in case)